### ISSUE TITLE
preprocessing error KeyError: 140227

### ISSUE THREAD

**Issue by Soonhwan-Kwon** [microsoft/SEED-Encoder#2]
I encountered KeyError: 140227 and below is the log of my script.
Error : 
Traceback (most recent call last):
  File "data/msmarco_data.py", line 518, in <module>
    main()
  File "data/msmarco_data.py", line 514, in main
    preprocess(args)
  File "data/msmarco_data.py", line 213, in preprocess
    "train-qrel.tsv")
  File "data/msmarco_data.py", line 122, in write_query_rel
    rel +
KeyError: 140227

Script : 
python data/msmarco_data.py --data_dir /raid/bae_sh/codes/ance/raw_data --out_data_dir ./preprocessed_data  --train_model_type rdot_nll_fairseq_fast --max_seq_length 512 --data_type 0 --bpe_vocab_file checkpoints_msmarco/vocab.txt

Log : 
start passage file split processing
start merging splits
0 1555982
1 3257085
2 898719
Total lines written: 1085721
First line
(512, array([    0, 19100,  1036,    30,    19,    19,  9519,    18, 28131,
          18,  1745,    19,  3814,    19,  8741,    35, 24792,  1045,
          33,  3292, 17346, 31158, 11400,  1072, 12714, 10327,  1083,
        1048,  1044,  1051,  1030,     2,  1653,  3324, 14373, 14489,
        1666,  4976, 32324,  4056,  1663,  1653,  2011,  1666, 21866,
       11856,    18,    35,     2,  3863,    10,  8937,  8767,  1653,
        3324, 14373, 14489,  1666,  4976, 32324,  4056,  1663,  1653,
        2011,  1666, 21866, 11856,    18,    35,  1706,  1705,    41,
        2343, 27441,  1674, 10673,  1719,  1653, 21384,  2194,  6271,
          45,  1705,  6927,  1674,    21,  1695,  2205, 14489,    18,
        2632,  1653, 17393,  1666,  1653,  2483,  7972,  1680,    16,
        1653,  5219,  3672,  2483,  1663,  1653, 21269, 21351,  1719,
       11301,  2059,  4056,  1722,    41,  5269,  1666,    22,    18,
          27,    64,  2476,    39,  5904,    63,  1670,  1891,    41,
        4894,  7278,  1666,  2797,    16, 26305,    51,    18, 10673,
        1719,  1653,  2483,  1705, 24444,    18,  2507,   242,    33,
          18,    18,    18,  2280,  1991,  2167,    23,  9519,  9519,
       25690,  8604, 20565,  6959,  2579,  4947,    30, 15675,    17,
       14202,  1052,  6573,  2546,  2438,  1719,  1653,  4056, 22333,
        1734, 11856,  1705, 18816,  1674,  1653,  7037,  2680,  1666,
        1653,  7278,    30,    57,    33,   228,    87,   242,    87,
          60,    39,    24,  1653,  3521,  4056, 22333,  1722,    41,
       24444,  4894,  1666, 17393,    58,  1705,    57,    33,    57,
          87,   239,    87,     3,    33,   228,    87,   242,    87,
          60,    39,    24,    87,   239,    87,     3,  8716,  1653,
       17393,  1705,    58,    33,     3,    12,    57,    19,    12,
         228,    87,   242,    87,    60,    39,    24,    87,   239,
          13,    13,    33,     3,    12,    22,    18,    27,  1049,
        7927,    15,  5904,    63,    19,    12,    21,    87,    25,
          18, 10211,  1049,  7927,    17,    28,  1083,    19,     3,
          39,    24,    87,    12, 30821,  1047,    13,    39,    24,
          87,   239,    13,    13,    33,    23,    18,  3623,  1049,
        7927,    15,  2890,    53,  4973,    12,    59,    13,    30,
       19100,    30,    19,    19,  1812,    18, 22904,    18, 13878,
          19, 16424,  1032,    19, 15675,    40, 14202,    18,    18,
          18, 14663, 28269,    87,    21,  8069,  4722,  1069,  1971,
        5123, 14663, 28269,    16,  1736, 12905,    41,    24,  1663,
        2102,  4947,    18,  2102,  5660,  2219,  3748,  1706,    30,
          52,    33,    24, 16807,    12,    58,    39,    22,    13,
       22250,    12,    60,    39,    24,    13,    18,  3220,    52,
          16, 19030, 16091,    16,  1702,  1653,  4056,  1663,  1803,
        4418,    16,  1736,  1878,  2632,  1653, 17393,    58,  1734,
        3643, 19839, 22202,    12,    52,    19,    12,    24, 16807,
       14422, 27240,  1029,    12,    60,    39,    24,    13,    13,
          18,  4168,  1803,  9795,  4031,    18, 12929,    87,    24,
        2154,  4722,  1086,    21,  5123,    12, 15675,    17, 14202,
        1052,  6573,  2546,    13,    52,    33,    24, 16807,    14,
          58,    39,    22,    14, 22250,    14,    60,    39,    24,
       18140,  1695,    58,  1827,  2131,    30,    33,    34,    58,
          33,    12,    21,    19,    12,    22,  1031,    39,    22,
          13,    13,    14, 19839, 22202,    12,    52,    19,    12,
       12650,    14, 22250,    13,    13, 16116,  3858,  1663,  2102,
        7563,  1736,  2405,  2131,    30,    33,    34,    58,    33,
          12,    21,    19,    12,    22,    12,  2797,    16, 26305,
        1047,    13,    39,    22,    13,    13,    14, 19839, 22202,
          12,    12,    22,    18,    27,    14,  2476,    39,  5904,
        1083,    13,    19,    12, 12650,    14,    12,    25],
      dtype=int32))
done saving pid2offset
Writing query files train-query and train-qrel.tsv
Loading query_2_pos_docid
start query file split processing
start merging splits
1 1185869
2 295446
done saving qid2offset
Total lines written: 367013
First line
(16, array([    0,    13,  1959,  1686,  1653,  8786,  5474,  1666,  1653,
        2834,  1666,  1653, 10881,  3012,    35,     2,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1], dtype=int32))
Writing qrels
Traceback (most recent call last):
  File "data/msmarco_data.py", line 518, in <module>
    main()
  File "data/msmarco_data.py", line 514, in main
    preprocess(args)
  File "data/msmarco_data.py", line 213, in preprocess
    "train-qrel.tsv")
  File "data/msmarco_data.py", line 122, in write_query_rel
    rel +
KeyError: 140227

**Comment by Soonhwan-Kwon** [comment]
I used files that I downloaded manually. And it doesn't occur after I re-downloaded it with provided command(commands/data_download.sh)
